<a href="https://colab.research.google.com/github/martynawl/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Podstawy**

In [ ]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D **Array**



In [ ]:
import numpy as np
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array([1.3, 2.3, 1.4])

array([1.3, 2.3, 1.4])

In [3]:
x = np.array([1, 3])

import numpy as np
x.dtype

dtype('int64')

2D **Array**

In [5]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [6]:
x.ndim

2

In [7]:
x.shape

(2, 2)

In [11]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [12]:
x.shape

(2, 3)

3D Array

In [18]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
      
      [[4, 1, 3],
       [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [19]:
x.ndim

3

In [20]:
x.shape

(2, 2, 3)

# Nowa sekcja