<a href="https://colab.research.google.com/github/martynawl/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algebra liniowa

Norma wektora, długość wektora w R(kwadrat)

In [ ]:
import numpy as np

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

Norma euklidesowa w R do n

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

5.0

Odległość dwóch punktów w przestrzeni R do n

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
             [0, -1, 2],
             [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [ ]:
import numpy as np
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Ślad *macierzy* - suma elementów na przekątnej

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa - ma tyle samo wierszy, co kolumn, której współczynniki na przekątnej są równe 1.

In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [ ]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [ ]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [ ]:
X.shape

(2, 1)

Funkcje statystyczne

In [2]:
import numpy as np
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [3]:
price.sum()

4650.1

In [4]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [6]:
np.sum(price)

4650.1

min()

In [7]:
np.min(price)

11.7

In [8]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

max()

In [9]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

median()

In [10]:
np.median(price)

12.6

mean()

In [12]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std()

In [14]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

var()

In [15]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])