<a href="https://colab.research.google.com/github/martynawl/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algebra liniowa

Norma wektora, długość wektora w R(kwadrat)

In [ ]:
import numpy as np

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

Norma euklidesowa w R do n

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

5.0

Odległość dwóch punktów w przestrzeni R do n

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
             [0, -1, 2],
             [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [3]:
import numpy as np
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Ślad *macierzy* - suma elementów na przekątnej

In [4]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa - ma tyle samo wierszy, co kolumn, której współczynniki na przekątnej są równe 1.

In [5]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [7]:
A

array([[ 2,  4],
       [-1,  3]])

In [10]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [13]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [15]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [16]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [17]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [21]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [24]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [25]:
X.shape

(2, 1)