<a href="https://colab.research.google.com/github/martynawl/data-science-bootcamp/blob/main/indeksowanie_i_wycinanie_tablic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Indeksowanie i wycinanie tablic

In [40]:
import numpy as np
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [4]:
A[2]

2

In [36]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [37]:
A[:2]

array([0, 1])

In [42]:
A[[0, 2]]

array([0, 2])

In [43]:
A[-1]

19

In [44]:
A[10:15]

array([10, 11, 12, 13, 14])

In [45]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
A[0]

array([0, 1, 2, 3, 4])

In [47]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [52]:
A[1, 1]


6

In [53]:
A[1, 3]

8

In [54]:
A[1:2, 1:4]

array([[6, 7, 8]])

In [30]:
A[1, 2] = 7
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])