<a href="https://colab.research.google.com/github/martynawl/data-science-bootcamp/blob/main/tworzenie_tablic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawowe operacje na tablicach

In [21]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [22]:
A + B

array([6, 0, 7, 4])

In [23]:
A -B

array([0, 2, 1, 0])

In [24]:
A * B

array([ 9, -1, 12,  4])

In [25]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [29]:
np.add(A, B)

array([6, 0, 7, 4])

In [30]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [31]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [32]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [26]:
A + 3

array([6, 4, 7, 5])

In [27]:
2 * A

array([6, 2, 8, 4])

In [28]:
A + 3*B

array([12, -2, 13,  8])

In [36]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [37]:
X * Y

array([[6, 0],
       [2, 0]])

In [38]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [39]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [40]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [41]:
X @ Y

array([[  3,   6],
       [-12,   0]])